/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcxiaoke_ndk_Native */

#ifndef _Included_com_mcxiaoke_ndk_Native
#define _Included_com_mcxiaoke_ndk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL native_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL native_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL native_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL native_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL native_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    renderBitmap
 * Signature: (JLandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL native_renderBitmap
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL native_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    initSurface
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL native_initSurface
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    renderOpenGL
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL native_renderOpenGL
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL native_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    initNW
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL native_initNW
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    renderNW
 * Signature: (JLandroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL native_renderNW
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
