/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_Native */

#ifndef _Included_com_example_hellojni_Native
#define _Included_com_example_hellojni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_Native
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_Native_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_Native
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_Native_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_Native
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_Native_nativeWorker
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_hellojni_Native
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_Native_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
