/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public class AsyncUidProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AsyncUidProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AsyncUidProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeJNI.delete_AsyncUidProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AsyncUidProvider() {
    this(NativeJNI.new_AsyncUidProvider(), true);
  }

  public void getUid() {
    NativeJNI.AsyncUidProvider_getUid(swigCPtr, this);
  }

  public void onUid(long uid) {
    NativeJNI.AsyncUidProvider_onUid(swigCPtr, this, uid);
  }

}
