/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public class MyClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MyClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeJNI.delete_MyClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MyClass() {
    this(NativeJNI.new_MyClass__SWIG_0(), true);
  }

  public MyClass(int x) {
    this(NativeJNI.new_MyClass__SWIG_1(x), true);
  }

  public String show() {
    return NativeJNI.MyClass_show(swigCPtr, this);
  }

}
