/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public interface NativeConstants {
  public final static int EXPRESSION = (0x100+5);
  public final static long BIG = NativeJNI.BIG_get();
  public final static java.math.BigInteger LARGE = NativeJNI.LARGE_get();
}
