/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public class Shape {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Shape(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Shape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeJNI.delete_Shape(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Shape() {
    this(NativeJNI.new_Shape__SWIG_0(), true);
  }

  public Shape(double a, double b) {
    this(NativeJNI.new_Shape__SWIG_1(a, b), true);
  }

  public void setX(double value) {
    NativeJNI.Shape_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return NativeJNI.Shape_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    NativeJNI.Shape_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return NativeJNI.Shape_y_get(swigCPtr, this);
  }

  public Shape move(double dx, double dy) {
    return new Shape(NativeJNI.Shape_move(swigCPtr, this, dx, dy), false);
  }

  public String info() {
    return NativeJNI.Shape_info(swigCPtr, this);
  }

  public double area() {
    return NativeJNI.Shape_area(swigCPtr, this);
  }

  public double perimeter() {
    return NativeJNI.Shape_perimeter(swigCPtr, this);
  }

  public static void setNshapes(int value) {
    NativeJNI.Shape_nshapes_set(value);
  }

  public static int getNshapes() {
    return NativeJNI.Shape_nshapes_get();
  }

}
