/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcxiaoke_ndk_Native */

#ifndef _Included_com_mcxiaoke_ndk_Native
#define _Included_com_mcxiaoke_ndk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_mcxiaoke_ndk_Native_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mcxiaoke_ndk_Native_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mcxiaoke_ndk_Native_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    getFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_mcxiaoke_ndk_Native_getFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mcxiaoke_ndk_Native_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    render
 * Signature: (JLandroid/graphics/Bitmap;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mcxiaoke_ndk_Native_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
