/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_example_helloapp_NativeUtils */

#ifndef _Included_com_example_helloapp_NativeUtils
#define _Included_com_example_helloapp_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloapp_NativeUtils
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloapp_NativeUtils_getTitle
  (JNIEnv *, jclass);

/*
 * Class:     com_example_helloapp_NativeUtils
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_helloapp_NativeUtils_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
