/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_livecamera_CameraView */

#ifndef _Included_com_demo_livecamera_CameraView
#define _Included_com_demo_livecamera_CameraView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_livecamera_CameraView
 * Method:    decode
 * Signature: (Landroid/graphics/Bitmap;[B)V
 */
JNIEXPORT void JNICALL Java_com_demo_livecamera_CameraView_decode
  (JNIEnv *, jobject, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
