/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.hellojni;

public interface UnixConstants {
  public final static int MAX_WIDTH = 640;
  public final static int MAX_HEIGHT = UnixJNI.MAX_HEIGHT_get();
  public final static int ONE = 1;
  public final static int TWO = 2;
  public final static int THREE = TWO + 1;
  public final static int FOUR = THREE + 1;

}
