/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcxiaoke_ndk_Native */

#ifndef _Included_com_mcxiaoke_ndk_Native
#define _Included_com_mcxiaoke_ndk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcxiaoke_ndk_Native
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mcxiaoke_ndk_Native_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
